### ISSUE TITLE
I can't access into chembl API

### ISSUE THREAD

**Issue by TarapongSrisongkram** [chembl/chembl_webresource_client#105] opened 2021-07-08 14:52 UTC
Hi! I have a problem when I want to access chembl API, I can install chembl_webresource, but I can't access into the database, it said that

`
ImportError: cannot import name '_encode' from 'requests_cache.cache_keys' (/Users/tarapongsrisongkram/my_env/lib/python3.9/site-packages/requests_cache/cache_keys.py)` 

Here is my code
`pip install chembl_webresource_client`

`from chembl_webresource_client.new_client import new_client`
<img width="1105" alt="Screen Shot 2564-07-08 at 21 48 41" src="https://user-images.githubusercontent.com/86768595/124942995-5131b500-e036-11eb-9459-269e3a62fee4.png">
<img width="1026" alt="Screen Shot 2564-07-08 at 21 48 46" src="https://user-images.githubusercontent.com/86768595/124943086-61e22b00-e036-11eb-9be0-c07b5951caef.png"> 

I've try run it on collab but it doesn't work either, how can i fix it ? any help is appreciate
P.S. I run on Python 3.9

**Comment by alleFarell** [comment] 2021-07-08 18:02
I have faced the same issue today

**Comment by eloyfelix** [comment] 2021-07-08 18:18
Hi, I can confirm the isue. The last version (0.7.0) of requests_cache broke the package. This also happened before when they released the 0.6.0.

If you install the previous version (0.6.4) it will work for you while we fix it.

```
pip install requests_cache==0.6.4
```

**Comment by alleFarell** [comment] 2021-07-08 18:49
it works, Thank you very much

**Comment by eloyfelix** [comment] 2021-07-08 22:28
new version 0.10.5 of chembl_webresource_client fixes the issue.

**Comment by JWCook** [comment] 2021-07-08 23:19
Sorry about that! A few tips for making this less prone to breakage:
* Pin dependencies to the latest minor version, for example. `requests-cache~=0.7.0`. That will allow updating for patch releases (`0.7.1`) but not major or minor releases (`0.8.0`).
* Internal functions (especially ones prefixed with `_`) are subject to change, so it's safer to stick to things documented as part of the [public API](https://requests-cache.readthedocs.io/en/stable/api.html).
* It looks like `chembl_webresource_client.cache` is patching out `BaseCache.create_key`, which may also potentially break with future updates. If you just want to take request headers into account, there's [an option for that](https://requests-cache.readthedocs.io/en/stable/user_guide.html#request-headers).
* If you need more control over how the cache keys are created, there's an open issue to support that (https://github.com/reclosedev/requests-cache/issues/284), so add comments there if that's a feature you'd like.

If you run into any more issues or have more questions, you're welcome to [create an issue on the requests-cache repo](https://github.com/reclosedev/requests-cache/issues/new/choose).

**Comment by TarapongSrisongkram** [comment] 2021-07-09 01:37
Hi! It work well, thank you for your response!

**Comment by eloyfelix** [comment] 2021-07-09 08:02
Many thanks for your suggestions @JWCook. I used them :)

Closing this.

**Closed** 2021-07-09 08:35 UTC
